const countryCodes = [
  { id: 1, country: "AFG", name: "Afghanistan", code: "+93" },
  { id: 2, country: "ALB", name: "Albania", code: "+355" },
  { id: 3, country: "DZA", name: "Algeria", code: "+213" },
  { id: 4, country: "AND", name: "Andorra", code: "+376" },
  { id: 5, country: "AGO", name: "Angola", code: "+244" },
  { id: 6, country: "ATG", name: "Antigua and Barbuda", code: "+1-268" },
  { id: 7, country: "ARG", name: "Argentina", code: "+54" },
  { id: 8, country: "ARM", name: "Armenia", code: "+374" },
  { id: 9, country: "AUS", name: "Australia", code: "+61" },
  { id: 10, country: "AUT", name: "Austria", code: "+43" },
  { id: 11, country: "AZE", name: "Azerbaijan", code: "+994" },
  { id: 12, country: "BHS", name: "Bahamas", code: "+1-242" },
  { id: 13, country: "BHR", name: "Bahrain", code: "+973" },
  { id: 14, country: "BGD", name: "Bangladesh", code: "+880" },
  { id: 15, country: "BRB", name: "Barbados", code: "+1-246" },
  { id: 16, country: "BLR", name: "Belarus", code: "+375" },
  { id: 17, country: "BEL", name: "Belgium", code: "+32" },
  { id: 18, country: "BLZ", name: "Belize", code: "+501" },
  { id: 19, country: "BEN", name: "Benin", code: "+229" },
  { id: 20, country: "BTN", name: "Bhutan", code: "+975" },
  { id: 21, country: "BOL", name: "Bolivia", code: "+591" },
  { id: 22, country: "BIH", name: "Bosnia and Herzegovina", code: "+387" },
  { id: 23, country: "BWA", name: "Botswana", code: "+267" },
  { id: 24, country: "BRA", name: "Brazil", code: "+55" },
  { id: 25, country: "BRN", name: "Brunei", code: "+673" },
  { id: 26, country: "BGR", name: "Bulgaria", code: "+359" },
  { id: 27, country: "BFA", name: "Burkina Faso", code: "+226" },
  { id: 28, country: "BDI", name: "Burundi", code: "+257" },
  { id: 29, country: "CPV", name: "Cabo Verde", code: "+238" },
  { id: 30, country: "KHM", name: "Cambodia", code: "+855" },
  { id: 31, country: "CMR", name: "Cameroon", code: "+237" },
  { id: 32, country: "CAN", name: "Canada", code: "+1" },
  { id: 33, country: "CAF", name: "Central African Republic", code: "+236" },
  { id: 34, country: "TCD", name: "Chad", code: "+235" },
  { id: 35, country: "CHL", name: "Chile", code: "+56" },
  { id: 36, country: "CHN", name: "China", code: "+86" },
  { id: 37, country: "COL", name: "Colombia", code: "+57" },
  { id: 38, country: "COM", name: "Comoros", code: "+269" },
  { id: 39, country: "COG", name: "Congo", code: "+242" },
  { id: 40, country: "CRI", name: "Costa Rica", code: "+506" },
  { id: 41, country: "HRV", name: "Croatia", code: "+385" },
  { id: 42, country: "CUB", name: "Cuba", code: "+53" },
  { id: 43, country: "CYP", name: "Cyprus", code: "+357" },
  { id: 44, country: "CZE", name: "Czech Republic", code: "+420" },
  { id: 45, country: "DNK", name: "Denmark", code: "+45" },
  { id: 46, country: "DJI", name: "Djibouti", code: "+253" },
  { id: 47, country: "DMA", name: "Dominica", code: "+1-767" },
  { id: 48, country: "DOM", name: "Dominican Republic", code: "+1-809" },
  { id: 49, country: "ECU", name: "Ecuador", code: "+593" },
  { id: 50, country: "EGY", name: "Egypt", code: "+20" },
  { id: 51, country: "SLV", name: "El Salvador", code: "+503" },
  { id: 52, country: "GNQ", name: "Equatorial Guinea", code: "+240" },
  { id: 53, country: "ERI", name: "Eritrea", code: "+291" },
  { id: 54, country: "EST", name: "Estonia", code: "+372" },
  { id: 55, country: "ETH", name: "Ethiopia", code: "+251" },
  { id: 56, country: "FJI", name: "Fiji", code: "+679" },
  { id: 57, country: "FIN", name: "Finland", code: "+358" },
  { id: 58, country: "FRA", name: "France", code: "+33" },
  { id: 59, country: "GAB", name: "Gabon", code: "+241" },
  { id: 60, country: "GMB", name: "Gambia", code: "+220" },
  { id: 61, country: "GEO", name: "Georgia", code: "+995" },
  { id: 62, country: "DEU", name: "Germany", code: "+49" },
  { id: 63, country: "GHA", name: "Ghana", code: "+233" },
  { id: 64, country: "GRC", name: "Greece", code: "+30" },
  { id: 65, country: "GRD", name: "Grenada", code: "+1-473" },
  { id: 66, country: "GTM", name: "Guatemala", code: "+502" },
  { id: 67, country: "GIN", name: "Guinea", code: "+224" },
  { id: 68, country: "GNB", name: "Guinea-Bissau", code: "+245" },
  { id: 69, country: "GUY", name: "Guyana", code: "+592" },
  { id: 70, country: "HTI", name: "Haiti", code: "+509" },
  { id: 71, country: "HND", name: "Honduras", code: "+504" },
  { id: 72, country: "HUN", name: "Hungary", code: "+36" },
  { id: 73, country: "ISL", name: "Iceland", code: "+354" },
  { id: 74, country: "IND", name: "India", code: "+91" },
  { id: 75, country: "IDN", name: "Indonesia", code: "+62" },
  { id: 76, country: "IRN", name: "Iran", code: "+98" },
  { id: 77, country: "IRQ", name: "Iraq", code: "+964" },
  { id: 78, country: "IRL", name: "Ireland", code: "+353" },
  { id: 79, country: "ISR", name: "Israel", code: "+972" },
  { id: 80, country: "ITA", name: "Italy", code: "+39" },
  { id: 81, country: "JAM", name: "Jamaica", code: "+1-876" },
  { id: 82, country: "JPN", name: "Japan", code: "+81" },
  { id: 83, country: "JOR", name: "Jordan", code: "+962" },
  { id: 84, country: "KAZ", name: "Kazakhstan", code: "+7" },
  { id: 85, country: "KEN", name: "Kenya", code: "+254" },
  { id: 86, country: "KIR", name: "Kiribati", code: "+686" },
  { id: 87, country: "KOR", name: "South Korea", code: "+82" },
  { id: 88, country: "KWT", name: "Kuwait", code: "+965" },
  { id: 89, country: "KGZ", name: "Kyrgyzstan", code: "+996" },
  { id: 90, country: "LAO", name: "Laos", code: "+856" },
  { id: 91, country: "LVA", name: "Latvia", code: "+371" },
  { id: 92, country: "LBN", name: "Lebanon", code: "+961" },
  { id: 93, country: "LSO", name: "Lesotho", code: "+266" },
  { id: 94, country: "LBR", name: "Liberia", code: "+231" },
  { id: 95, country: "LBY", name: "Libya", code: "+218" },
  { id: 96, country: "LIE", name: "Liechtenstein", code: "+423" },
  { id: 97, country: "LTU", name: "Lithuania", code: "+370" },
  { id: 98, country: "LUX", name: "Luxembourg", code: "+352" },
  { id: 99, country: "MDG", name: "Madagascar", code: "+261" },
  { id: 100, country: "MWI", name: "Malawi", code: "+265" },
  { id: 101, country: "MYS", name: "Malaysia", code: "+60" },
  { id: 102, country: "MDV", name: "Maldives", code: "+960" },
  { id: 103, country: "MLI", name: "Mali", code: "+223" },
  { id: 104, country: "MLT", name: "Malta", code: "+356" },
  { id: 105, country: "MHL", name: "Marshall Islands", code: "+692" },
  { id: 106, country: "MRT", name: "Mauritania", code: "+222" },
  { id: 107, country: "MUS", name: "Mauritius", code: "+230" },
  { id: 108, country: "MEX", name: "Mexico", code: "+52" },
  { id: 109, country: "FSM", name: "Micronesia", code: "+691" },
  { id: 110, country: "MDA", name: "Moldova", code: "+373" },
  { id: 111, country: "MCO", name: "Monaco", code: "+377" },
  { id: 112, country: "MNG", name: "Mongolia", code: "+976" },
  { id: 113, country: "MNE", name: "Montenegro", code: "+382" },
  { id: 114, country: "MAR", name: "Morocco", code: "+212" },
  { id: 115, country: "MOZ", name: "Mozambique", code: "+258" },
  { id: 116, country: "MMR", name: "Myanmar", code: "+95" },
  { id: 117, country: "NAM", name: "Namibia", code: "+264" },
  { id: 118, country: "NRU", name: "Nauru", code: "+674" },
  { id: 119, country: "NPL", name: "Nepal", code: "+977" },
  { id: 120, country: "NLD", name: "Netherlands", code: "+31" },
  { id: 121, country: "NZL", name: "New Zealand", code: "+64" },
  { id: 122, country: "NIC", name: "Nicaragua", code: "+505" },
  { id: 123, country: "NER", name: "Niger", code: "+227" },
  { id: 124, country: "NGA", name: "Nigeria", code: "+234" },
  { id: 125, country: "MKD", name: "North Macedonia", code: "+389" },
  { id: 126, country: "NOR", name: "Norway", code: "+47" },
  { id: 127, country: "OMN", name: "Oman", code: "+968" },
  { id: 128, country: "PAK", name: "Pakistan", code: "+92" },
  { id: 129, country: "PLW", name: "Palau", code: "+680" },
  { id: 130, country: "PSE", name: "Palestine", code: "+970" },
  { id: 131, country: "PAN", name: "Panama", code: "+507" },
  { id: 132, country: "PNG", name: "Papua New Guinea", code: "+675" },
  { id: 133, country: "PRY", name: "Paraguay", code: "+595" },
  { id: 134, country: "PER", name: "Peru", code: "+51" },
  { id: 135, country: "PHL", name: "Philippines", code: "+63" },
  { id: 136, country: "POL", name: "Poland", code: "+48" },
  { id: 137, country: "PRT", name: "Portugal", code: "+351" },
  { id: 138, country: "QAT", name: "Qatar", code: "+974" },
  { id: 139, country: "ROU", name: "Romania", code: "+40" },
  { id: 140, country: "RUS", name: "Russia", code: "+7" },
  { id: 141, country: "RWA", name: "Rwanda", code: "+250" },
  { id: 142, country: "KNA", name: "Saint Kitts and Nevis", code: "+1-869" },
  { id: 143, country: "LCA", name: "Saint Lucia", code: "+1-758" },
  {
    id: 144,
    country: "VCT",
    name: "Saint Vincent and the Grenadines",
    code: "+1-784",
  },
  { id: 145, country: "WSM", name: "Samoa", code: "+685" },
  { id: 146, country: "SMR", name: "San Marino", code: "+378" },
  { id: 147, country: "STP", name: "Sao Tome and Principe", code: "+239" },
  { id: 148, country: "SAU", name: "Saudi Arabia", code: "+966" },
  { id: 149, country: "SEN", name: "Senegal", code: "+221" },
  { id: 150, country: "SRB", name: "Serbia", code: "+381" },
  { id: 151, country: "SYC", name: "Seychelles", code: "+248" },
  { id: 152, country: "SLE", name: "Sierra Leone", code: "+232" },
  { id: 153, country: "SGP", name: "Singapore", code: "+65" },
  { id: 154, country: "SVK", name: "Slovakia", code: "+421" },
  { id: 155, country: "SVN", name: "Slovenia", code: "+386" },
  { id: 156, country: "SLB", name: "Solomon Islands", code: "+677" },
  { id: 157, country: "SOM", name: "Somalia", code: "+252" },
  { id: 158, country: "ZAF", name: "South Africa", code: "+27" },
  { id: 159, country: "ESP", name: "Spain", code: "+34" },
  { id: 160, country: "LKA", name: "Sri Lanka", code: "+94" },
  { id: 161, country: "SDN", name: "Sudan", code: "+249" },
  { id: 162, country: "SUR", name: "Suriname", code: "+597" },
  { id: 163, country: "SWE", name: "Sweden", code: "+46" },
  { id: 164, country: "CHE", name: "Switzerland", code: "+41" },
  { id: 165, country: "SYR", name: "Syria", code: "+963" },
  { id: 166, country: "TWN", name: "Taiwan", code: "+886" },
  { id: 167, country: "TJK", name: "Tajikistan", code: "+992" },
  { id: 168, country: "TZA", name: "Tanzania", code: "+255" },
  { id: 169, country: "THA", name: "Thailand", code: "+66" },
  { id: 170, country: "TLS", name: "Timor-Leste", code: "+670" },
  { id: 171, country: "TGO", name: "Togo", code: "+228" },
  { id: 172, country: "TON", name: "Tonga", code: "+676" },
  { id: 173, country: "TTO", name: "Trinidad and Tobago", code: "+1-868" },
  { id: 174, country: "TUN", name: "Tunisia", code: "+216" },
  { id: 175, country: "TUR", name: "Turkey", code: "+90" },
  { id: 176, country: "TKM", name: "Turkmenistan", code: "+993" },
  { id: 177, country: "TUV", name: "Tuvalu", code: "+688" },
  { id: 178, country: "UGA", name: "Uganda", code: "+256" },
  { id: 179, country: "UKR", name: "Ukraine", code: "+380" },
  { id: 180, country: "ARE", name: "United Arab Emirates", code: "+971" },
  { id: 181, country: "GBR", name: "United Kingdom", code: "+44" },
  { id: 182, country: "USA", name: "United States", code: "+1" },
  { id: 183, country: "URY", name: "Uruguay", code: "+598" },
  { id: 184, country: "UZB", name: "Uzbekistan", code: "+998" },
  { id: 185, country: "VUT", name: "Vanuatu", code: "+678" },
  { id: 186, country: "VEN", name: "Venezuela", code: "+58" },
  { id: 187, country: "VNM", name: "Vietnam", code: "+84" },
  { id: 188, country: "YEM", name: "Yemen", code: "+967" },
  { id: 189, country: "ZMB", name: "Zambia", code: "+260" },
  { id: 190, country: "ZWE", name: "Zimbabwe", code: "+263" },
];
