import { GraphqlProvider } from "@/modules/shared/components/graphql-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GraphqlProvider>
        <body>{children}</body>
      </GraphqlProvider>
    </html>
  );
}
